[package]
name = "ql2"
description = "RethinkDB protocol; data structures and traits"
version = "1.1.0-alpha.1"
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-rethinkdb/ql2"
documentation = "https://docs.rs/ql2"
readme = "README.md"
keywords = ["database", "rethinkdb", "reql", "ql2"]
authors = ["rushmorem <rushmore@webenchanter.com>"]

build = "build.rs"

[dependencies]
r2d2 = "0.7"
protobuf = "1.0"
byteorder = "0.5"
bufstream = "0.1"
serde = "0.8"
serde_json = "0.8"
uuid = { version = "0.3", features = ["v4", "serde", "use_std"] }
scram = "0.1"
quick-error = "1.1"
futures = "0.1"

[build-dependencies]
skeptic = "0.6"
serde_codegen = "0.8"

[dev-dependencies]
skeptic = "0.6"
